services:
  server:
    container_name: API-ButcherProject-Server
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - .env
    links:
      - database
    volumes:
      - .:/usr/src/app
  database:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - ${TYPEORM_PORT}:5432
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
